apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer-deployment
  labels:
    app: producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: producer
  template:
    metadata:
      labels:
        app: producer
    spec:
      containers:
        - name: producer
          image: chanthruuthaya/producer:latest
          env:
            - name: TOKEN
              value: /var/run/secrets/kubernetes.io/serviceaccount/token
          ports:
          - containerPort: 5000